IMPORT * FROM ML;
IMPORT * FROM $;
lymphomaData:= lymphomaDS.DS;
OUTPUT(lymphomaData, NAMED('lymphomaData'), ALL);
ML.ToField(lymphomaData, full_ds);
OUTPUT(full_ds_Map,ALL, NAMED('DatasetFieldMap'));
indepData:= full_ds(number<4027);
depData:= ML.Discretize.ByRounding(full_ds(number=4027));
minNumObj:= 2;    maxLevel := 10;
trainer1:= ML.Classify.DecisionTree.C45Binary(minNumObj, maxLevel); 
tmod:= trainer1.LearnC(indepData, depData);
tmodel:= trainer1.Model(tmod);
OUTPUT(SORT(tmodel, node_id, new_node_id), ALL, NAMED('TreeModel'));
results1:= trainer1.ClassifyC(indepData, tmod);
OUTPUT(results1, ALL, NAMED('ClassificationResults'));
OUTPUT(TABLE(results1, {closest_conf, cnt:= COUNT(GROUP)}, closest_conf), NAMED('FinalNodeAssig1'));
results11:= Classify.Compare(PROJECT(depData, TRANSFORM(Types.DiscreteField,SELF.number:=1, SELF:=LEFT)), results1);
OUTPUT(results11.CrossAssignments, NAMED('CrossAssig1'));
OUTPUT(results11.RecallByClass, NAMED('RecallByClass1'));
OUTPUT(results11.PrecisionByClass, NAMED('PrecisionByClass1'));